# Generated by Django 5.0.1 on 2024-02-11 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpasscode',
            name='pass_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Numeric Field. Only 4 digits allowed.', regex='^\\+?1?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='verifiedpasscode',
            name='verified_pass_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Numeric Field. Only 4 digits allowed.', regex='^\\+?1?\\d{4}$')]),
        ),
    ]
