# Generated by Django 5.0.1 on 2024-04-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellet', '0003_alter_cardpasscode_pass_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='card_amount',
            field=models.PositiveIntegerField(default=20000, verbose_name='account on card'),
        ),
    ]
